enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
arch = "arm64-v8a"
build-mode = "both"
included-patches = "'Hide ads' 'Video ads' 'Disable auto captions' 'Hide video action buttons' 'Navigation buttons' 'Disable fullscreen ambient mode' 'Hide layout components' 'Hide player flyout menu items' 'Hide Shorts components' 'Miniplayer' 'Disable player popup panels' 'SponsorBlock' 'Remove background playback restrictions' 'Remove tracking query parameter' 'Force original audio' 'Remember video quality' 'Restore old video quality menu'"
exclusive-patches = true
